variable "vapp_name" {}
variable "name" {}
variable "catalog_name" {}
variable "template_name" {}
variable "memory" {}
variable "cpus" {}
variable "cpu_cores" {}
variable "power_on" {}
variable "accept_all_eulas" {}
variable "expose_hardware_virtualization" {}
